CREATE SEQUENCE INV_APPLICATION_SEQ START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;
CREATE SEQUENCE INV_APPLICATION_AUD_SEQ START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;

CREATE SEQUENCE INV_CATEGORY_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE INV_CATEGORY_AUD_SEQ START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;

CREATE SEQUENCE INV_SYSTEM_TYPE_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE INV_SYSTEM_TYPE_AUD_SEQ START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;

CREATE SEQUENCE INV_STATUS_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE INV_FIELD_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE INV_FIELD_AUD_SEQ START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;

CREATE SEQUENCE INV_ADM_UNIT_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE INV_ADM_UNIT_AUD_SEQ START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;

CREATE SEQUENCE INV_COMMISSION_SEQ START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE INV_COMMISSION_AUD_SEQ START WITH 1 INCREMENT BY 1 CACHE 50 NOCYCLE;
