ALTER TABLE INV_STATUS
    ADD CONSTRAINT INV_STATUS_PK PRIMARY KEY (STATUS_ID) USING INDEX INV_STATUS_PK_I;

ALTER TABLE INV_CATEGORY
    ADD CONSTRAINT INV_CATEGORY_PK PRIMARY KEY (CATEGORY_ID) USING INDEX INV_CATEGORY_PK_I;

ALTER TABLE INV_SYSTEM_TYPE
    ADD CONSTRAINT INV_SYSTEM_TYPE_PK PRIMARY KEY (SYSTEM_TYPE_ID) USING INDEX INV_SYSTEM_TYPE_PK_I;

ALTER TABLE INV_FIELD
    ADD CONSTRAINT INV_FIELD_PK PRIMARY KEY (FIELD_ID) USING INDEX INV_FIELD_PK_I;

ALTER TABLE INV_ADM_UNIT
    ADD CONSTRAINT INV_ADM_UNIT_PK PRIMARY KEY (ADM_UNIT_ID) USING INDEX INV_ADM_UNIT_PK_I;

ALTER TABLE INV_COMMISSION
    ADD CONSTRAINT INV_COMMISSION_PK PRIMARY KEY (COMMISSION_ID) USING INDEX INV_COMMISSION_PK_I;

ALTER TABLE INV_APPLICATION
    ADD CONSTRAINT INV_APPLICATION_PK PRIMARY KEY (APP_APPLICATION_ID) USING INDEX INV_APPLICATION_PK_I;

ALTER TABLE INV_CATEGORY_AUD
    ADD CONSTRAINT INV_CATEGORY_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_CATEGORY_AUD_PK_I;

ALTER TABLE INV_SYSTEM_TYPE_AUD
    ADD CONSTRAINT INV_SYSTEM_TYPE_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_SYSTEM_TYPE_AUD_PK_I;

ALTER TABLE INV_FIELD_AUD
    ADD CONSTRAINT INV_FIELD_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_FIELD_AUD_PK_I;

ALTER TABLE INV_ADM_UNIT_AUD
    ADD CONSTRAINT INV_ADM_UNIT_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_ADM_UNIT_AUD_PK_I;

ALTER TABLE INV_COMMISSION_AUD
    ADD CONSTRAINT INV_COMMISSION_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_COMMISSION_AUD_PK_I;

ALTER TABLE INV_APPLICATION_AUD
    ADD CONSTRAINT INV_APPLICATION_AUD_PK PRIMARY KEY (AUDIT_ID) USING INDEX INV_APPLICATION_AUD_PK_I;

ALTER TABLE INV_APPLICATION
    ADD CONSTRAINT INV_APPLICATION_CATEGORY_FK FOREIGN KEY (CATEGORY_ID) REFERENCES INV_CATEGORY (CATEGORY_ID);

ALTER TABLE INV_APPLICATION
    ADD CONSTRAINT INV_APPLICATION_SYSTEM_TYPE_FK FOREIGN KEY (SYSTEM_TYPE_ID) REFERENCES INV_SYSTEM_TYPE (SYSTEM_TYPE_ID);

ALTER TABLE INV_APPLICATION
    ADD CONSTRAINT INV_APPLICATION_FIELD_FK FOREIGN KEY (FIELD_ID) REFERENCES INV_FIELD (FIELD_ID);

ALTER TABLE INV_APPLICATION
    ADD CONSTRAINT INV_APPLICATION_ADM_UNIT_FK FOREIGN KEY (ADM_UNIT_ID) REFERENCES INV_ADM_UNIT (ADM_UNIT_ID);

ALTER TABLE INV_APPLICATION
    ADD CONSTRAINT INV_APPLICATION_COMMISSION_FK FOREIGN KEY (COMMISSION_ID) REFERENCES INV_COMMISSION (COMMISSION_ID);

ALTER TABLE INV_APPLICATION
    ADD CONSTRAINT INV_APPLICATION_STATUS_FK FOREIGN KEY (STATUS_ID) REFERENCES INV_STATUS (STATUS_ID);