# --- Configuración Base Local ---
spring.application.name=invai

# --- CORS para tu Front End en local ---
app.cors.allowed-origin=http://localhost:3000

# --- OAuth2 / Soffid (Redirección a tu Máquina Local) ---
spring.security.oauth2.client.registration.soffid.client-id=goib-default-des
spring.security.oauth2.client.registration.soffid.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.soffid.redirect-uri=http://localhost:8080/invaiapi/login/oauth2/code/soffid
spring.security.oauth2.client.registration.soffid.scope=openid
spring.security.oauth2.client.registration.soffid.client-authentication-method=none

# --- Proveedor IDP Soffid ---
spring.security.oauth2.client.provider.soffid.authorization-uri=https://idp.caib.es/auth/realms/soffid/protocol/openid-connect/auth
spring.security.oauth2.client.provider.soffid.token-uri=https://idp.caib.es/auth/realms/soffid/protocol/openid-connect/token
spring.security.oauth2.client.provider.soffid.user-info-uri=https://idp.caib.es/auth/realms/soffid/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.soffid.user-name-attribute=preferred_username
spring.security.oauth2.client.provider.soffid.jwk-set-uri=https://idp.caib.es/auth/realms/soffid/protocol/openid-connect/certs

# --- Niveles de Trazas en Local ---
logging.level.root=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.security=TRACE

# --- Conexión de Persistencia ---
spring.datasource.jndi-name=java:jboss/datasources/invaiDS
es.caib.invai.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
es.caib.invai.hibernate.query.substitutions=true 1, false 0

# Visualización de SQL activa en local para depurar
es.caib.invai.hibernate.show_sql=true
es.caib.invai.hibernate.format_sql=true

es.caib.invai.login.host=http://localhost:8080/invaiapi/