# System configuration properties for invai.
# The location of this file must be registered using the system property:
# es.caib.invai.system.properties (see section 3.5.2 of the standards)
# (This file uses UTF-8 encoding)

# --- Base Application Configuration ---
spring.application.name=invai

# --- CORS Entorno Servidor ---
app.cors.allowed-origin=https://invai.plexus.services
#app.cors.allowed-origin=http://localhost:8080


# --- OAuth2 / Soffid Configuration ---
spring.security.oauth2.client.registration.soffid.issuer=https://idp.caib.es
spring.security.oauth2.client.registration.soffid.client-id=goib-default-des
spring.security.oauth2.client.registration.soffid.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.soffid.redirect-uri=https://invai.plexus.services/invaiapi/login/oauth2/code/soffid
#spring.security.oauth2.client.registration.soffid.redirect-uri=http://localhost:8080/invaiapi/login/oauth2/code/soffid
spring.security.oauth2.client.registration.soffid.scope=openid
spring.security.oauth2.client.registration.soffid.client-authentication-method=none

# --- Soffid Provider Settings ---
spring.security.oauth2.client.provider.soffid.authorization-uri=https://idp.caib.es/auth/realms/soffid/protocol/openid-connect/auth
spring.security.oauth2.client.provider.soffid.token-uri=https://idp.caib.es/auth/realms/soffid/protocol/openid-connect/token
spring.security.oauth2.client.provider.soffid.user-info-uri=https://idp.caib.es/auth/realms/soffid/protocol/openid-connect/userinfo
spring.security.oauth2.client.provider.soffid.user-name-attribute=preferred_username
spring.security.oauth2.client.provider.soffid.jwk-set-uri=https://idp.caib.es/auth/realms/soffid/protocol/openid-connect/certs

# --- Logging Configuration ---
logging.level.root=DEBUG
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.security=TRACE

# --- Database and Hibernate Configuration ---
spring.datasource.jndi-name=java:jboss/datasources/invaiDS

# Hibernate Dialect
es.caib.invai.hibernate.dialect=org.hibernate.dialect.Oracle12cDialect
es.caib.invai.hibernate.query.substitutions=true 1, false 0

# SQL Debug logging properties
es.caib.invai.hibernate.show_sql=true
es.caib.invai.hibernate.format_sql=true

es.caib.invai.login.host=https://invai.plexus.services/invaiapi/
es.caib.invai.front.url.success=https://invai.plexus.services/invaifront/ca/aplicacions

#es.caib.invai.login.host=http://localhost:8080/invaiapi/
#es.caib.invai.front.url.success=http://localhost:8080/invaifront/ca/aplicacions

es.caib.invai.idp.logout.url=https://idp.caib.es/logout

server.servlet.session.timeout=12h
server.servlet.session.cookie.max-age=43200