import { FILE_MANAGEMENT_ROUTES_LOC } from './file-management.routes';
import { MAINTENANCES_ROUTES_LOC } from './maintenances.routes';

export const FULL_ROUTES = {
  HOME: '/',
  FILE_MANAGEMENT: {
    APPLICATION: {
      ELECTRONIC_PROCEDURES:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.APPLICATION.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.APPLICATION.ELECTRONIC_PROCEDURES,
      INBOX:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.APPLICATION.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.APPLICATION.INBOX,
      NEW:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.APPLICATION.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.APPLICATION.NEW,
    },
    DISABILITY_ASSESSMENTS: {
      BASE:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.DISABILITY_ASSESSMENTS.BASE,
      REPORT_MANAGEMENT:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.DISABILITY_ASSESSMENTS.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.DISABILITY_ASSESSMENTS.REPORT_MANAGEMENT.BASE,
    },
    FILE_CONSULTATION: {
      CONSULT:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.FILE_CONSULTATION.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.FILE_CONSULTATION.CONSULT,
    },
    INITIAL_PROCEDURES: {
      RECORDING:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.INITIAL_PROCEDURES.RECORDING,
    },
    MEETING: {
      DISABILITY_ASSESSMENT_MEETINGS:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.MEETING.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.MEETING.DISABILITY_ASSESSMENT_MEETINGS.BASE,
    },
    PERSONS: {
      SEARCH:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.PERSONS.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.PERSONS.SEARCH,
    },
    REQUIREMENTS: {
      SEARCH:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.REQUIREMENTS.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.REQUIREMENTS.SEARCH,
    },
    WAIT_LIST: {
      BASE: FILE_MANAGEMENT_ROUTES_LOC.BASE + '/' + FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.BASE,
      GENERAL_LIST:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.GENERAL_LIST.BASE,

      RESERVE_LIST:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.RESERVE_LIST.BASE,

      ASSIGNMENT_LIST:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.ASSIGNMENT_LIST.BASE,

      OCCUPATION_LIST:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.WAIT_LIST.OCCUPATION_LIST.BASE,
    },
    PENDING_PRESENTATION: {
      SEARCH:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.PENDING_PRESENTATION.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.PENDING_PRESENTATION.SEARCH,
    },
    RESOLUTIONS: {
      DEGREE:
        FILE_MANAGEMENT_ROUTES_LOC.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.RESOLUTIONS.BASE +
        '/' +
        FILE_MANAGEMENT_ROUTES_LOC.RESOLUTIONS.DEGREE.BASE,
    },
  },
  MAINTENANCES: {
    USER_MANAGEMENT: MAINTENANCES_ROUTES_LOC.BASE + '/' + MAINTENANCES_ROUTES_LOC.USER_MANAGEMENT,
    CENTERS_MANAGEMENT:
      MAINTENANCES_ROUTES_LOC.BASE + '/' + MAINTENANCES_ROUTES_LOC.CENTERS_MANAGEMENT,
    ASSOCIATION_MANAGEMENT:
      MAINTENANCES_ROUTES_LOC.BASE + '/' + MAINTENANCES_ROUTES_LOC.ASSOCIATION_MANAGEMENT,
  },
  ADMINISTRATION: {
    SQL: MAINTENANCES_ROUTES_LOC.BASE + '/' + MAINTENANCES_ROUTES_LOC.SQL,
  },
};
