export const MAINTENANCES_ROUTES_LOC = {
  BASE: $localize`gestions`,
  HOLIDAYS: $localize`dies-festius`,
  LEGAL_ENTITY: $localize`entitat-juridica`,
  MEMBER_ASSESSMENT: $localize`membres-organ`,
  REQUISITES: $localize`requisits`,
  USER_MANAGEMENT: $localize`gestio-usuaris`,
  SQL: $localize`sql`,
  CENTERS_MANAGEMENT: $localize`gestio-centres`,
  CREATE_CENTER: $localize`crear-centres`,
  SVODD: $localize`svodd`,
  ASSOCIATION_MANAGEMENT: $localize`gestio-associacions`,
  UNAUTHORIZE: $localize`no-autoritzat`,
  CENTERS: {
    BASE: $localize`centres`,
    AGREEMENTS: $localize`concerts`,
    INCIDENTS_WITHDRAWAL: $localize`incidencies-baixa`,
    INCIDENTS_OCCUPANCY: $localize`incidencies-ocupacio`,
    COST_GRADE: $localize`cost-grau`,
    MIN_FINANCING: $localize`min-financiacio`,
    HEALTH_PARTNER: $localize`socio-sanitaris`,
  },
  SCENARIOS: {
    BASE: $localize`escenaris`,
    SERVICE_PORTFOLIO: $localize`cartera-serveis`,
    MINIMUM_PENSIONS: $localize`pensions-minimes`,
    HERITAGE_PERCENTAGE: $localize`heritage-percentage`,
    ANNUAL_VARIABLE: $localize`variable-anual`,
    REFERENCE_PRICES: $localize`preus-referencia`,
  },
  SAD: {
    BASE: $localize`sad`,
    CONTRACTS: $localize`contractes`,
    HOUR_PRICES: $localize`preu-hores`,
    INCIDENTS_WITHDRAWAL: $localize`incidencies-baixa`,
    INCIDENTS_OCCUPANCY: $localize`incidencies-ocupacio`,
  },
  SAD_LINKED: {
    BASE: $localize`sad-vinculada`,
    PROVIDERS: $localize`proveidors`,
    INCIDENTS_WITHDRAWAL: $localize`incidencies-baixa`,
  },
  PERSONS: {
    BASE: $localize`persones`,
    MANAGEMENT: $localize`exitus-gestio`,
    IMSERSO: $localize`exitus-imserso`,
  },
  PAYROLL: {
    BASE: $localize`nomina`,
    MANAGEMENT: $localize`partida-presupuestaria`,
  },
  TRANSFER_AGENCIES: 'organismes-trasllat',
  INCIDENT_TITLE: $localize` títols-incidència`,
  DEPARTMENTS: $localize`departaments`,
};

export const MAINTENANCES_ROUTES_LOC_IDS = {
  MAINTENANCES_CENTERS_CREATE: 'MAINTENANCES_CENTERS_CREATE',
  MAINTENANCES_ZONES: 'MAINTENANCES_ZONES',
  MAINTENANCES_USER_MANAGEMENT: 'MAINTENANCES_USER_MANAGEMENT',
  MAINTENANCES_CENTERS_MANAGEMENT: 'MAINTENANCES_CENTERS_MANAGEMENT',
  MAINTENANCES_SCENARIOS_SERVICE_PORTFOLIO:
    'MAINTENANCES_SCENARIOS_SERVICE_PORTFOLIO',
  MAINTENANCES_SCENARIOS_REFERENCE_PRICES:
    'MAINTENANCES_SCENARIOS_REFERENCE_PRICES',
  MAINTENANCES_SCENARIOS_MINIMUM_PENSIONS:
    'MAINTENANCES_SCENARIOS_MINIMUM_PENSIONS',
  MAINTENANCES_SCENARIOS_HERITAGE_PERCENTAGE:
    'MAINTENANCES_SCENARIOS_HERITAGE_PERCENTAGE',
  MAINTENANCES_SCENARIOS_ANNUAL_VARIABLE:
    'MAINTENANCES_SCENARIOS_ANNUAL_VARIABLE',
  MAINTENANCES_SAD_LINKED_PROVIDERS: 'MAINTENANCES_SAD_LINKED_PROVIDERS',
  MAINTENANCES_SAD_LINKED_INCIDENTS_WITHDRAWAL:
    'MAINTENANCES_SAD_LINKED_INCIDENTS_WITHDRAWAL',
  MAINTENANCES_SAD_INCIDENTS_WITHDRAWAL:
    'MAINTENANCES_SAD_INCIDENTS_WITHDRAWAL',
  MAINTENANCES_SAD_INCIDENTS_OCCUPANCY: 'MAINTENANCES_SAD_INCIDENTS_OCCUPANCY',
  MAINTENANCES_SAD_HOUR_PRICES: 'MAINTENANCES_SAD_HOUR_PRICES',
  MAINTENANCES_SAD_CONTRACTS: 'MAINTENANCES_SAD_CONTRACTS',
  MAINTENANCES_REQUISITES: 'MAINTENANCES_REQUISITES',
  MAINTENANCES_PERSONS_EXITUS_MANAGEMENT:
    'MAINTENANCES_PERSONS_EXITUS_MANAGEMENT',
  MAINTENANCES_PERSONS_EXITUS_IMSERSO: 'MAINTENANCES_PERSONS_EXITUS_IMSERSO',
  MAINTENANCES_MEMBER_ASSESSMENT: 'MAINTENANCES_MEMBER_ASSESSMENT',
  MAINTENANCES_LEGAL_ENTITY: 'MAINTENANCES_LEGAL_ENTITY',
  MAINTENANCES_HOLIDAYS: 'MAINTENANCES_HOLIDAYS',
  MAINTENANCES_CENTERS_MIN_FINANCING: 'MAINTENANCES_CENTERS_MIN_FINANCING',
  MAINTENANCES_CENTERS_INCIDENTS_WITHDRAWAL:
    'MAINTENANCES_CENTERS_INCIDENTS_WITHDRAWAL',
  MAINTENANCES_CENTERS_INCIDENTS_OCCUPANCY:
    'MAINTENANCES_CENTERS_INCIDENTS_OCCUPANCY',
  MAINTENANCES_CENTERS_HEALTH_PARTNER: 'MAINTENANCES_CENTERS_HEALTH_PARTNER',
  MAINTENANCES_CENTERS_COST_GRADE: 'MAINTENANCES_CENTERS_COST_GRADE',
  MAINTENANCES_CENTERS_AGREEMENTS: 'MAINTENANCES_CENTERS_AGREEMENTS',
  MAINTENANCES_SVODD: 'MAINTENANCES_SVODD',
  MAINTENANCES_TEAM: 'MAINTENANCES_TEAM',
  MAINTENANCES_ASSOCIATION_MANAGEMENT: 'MAINTENANCES_ASSOCIATION_MANAGEMENT',
  MAINTENANCES_TRANSFER_AGENCIES: 'MAINTENANCES_TRANSFER_AGENCIES',
  MAINTENANCES_PAYROLL_BUDGET_LINES: 'MAINTENANCES_PAYROLL_BUDGET_LINES',
  MAINTENANCES_INCIDENT_TITLE: 'MAINTENANCES_INCIDENT_TITLE',
  MAINTENANCES_DEPARTMENTS: 'MAINTENANCES_DEPARTMENTS',
  ADMINISTRATION_SQL_CONSOLE: 'ADMINISTRATION_SQL_CONSOLE',
};
