-- FK / consultas
CREATE INDEX INV_APPLICATION_CATEGORY_ID_I ON INV_APPLICATION (CATEGORY_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_SYSTEM_TYPE_ID_I ON INV_APPLICATION (SYSTEM_TYPE_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_FIELD_ID_I ON INV_APPLICATION (FIELD_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_ADM_UNIT_ID_I ON INV_APPLICATION (ADM_UNIT_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_COMMISSION_ID_I ON INV_APPLICATION (COMMISSION_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_STATUS_ID_I ON INV_APPLICATION (STATUS_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APPLICATION_NAME_I ON INV_APPLICATION (LOWER(NAME)) TABLESPACE INVAI_INDEX;-- ➕ NUEVOS: Índices funcionales para evitar Full Table Scan al buscar por Código o Prefijo
CREATE INDEX INV_APPLICATION_CODE_FUNC_I ON INV_APPLICATION (LOWER(CODE)) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_PREFIX_FUNC_I ON INV_APPLICATION (LOWER(PREFIX)) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APPLICATION_CREATED_AT_I ON INV_APPLICATION (CREATED_AT) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_STATUS_EXPIRATION_I ON INV_APPLICATION (STATUS_ID, EXPIRATION_DATE) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_ACTIVE_STAT_I ON INV_APPLICATION (DELETED_AT, STATUS_ID) TABLESPACE INVAI_INDEX;

CREATE INDEX INV_APPLICATION_AUD_APPLICATION_ID_I ON INV_APPLICATION_AUD (APP_APPLICATION_ID) TABLESPACE INVAI_INDEX;
CREATE INDEX INV_APPLICATION_AUD_AUDIT_DATE_I ON INV_APPLICATION_AUD (AUDIT_DATE) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_CATEGORY_PK_I ON INV_CATEGORY (CATEGORY_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SYSTEM_TYPE_PK_I ON INV_SYSTEM_TYPE (SYSTEM_TYPE_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_STATUS_PK_I ON INV_STATUS (STATUS_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_FIELD_PK_I ON INV_FIELD (FIELD_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_ADM_UNIT_PK_I ON INV_ADM_UNIT (ADM_UNIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_COMMISSION_PK_I ON INV_COMMISSION (COMMISSION_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APPLICATION_PK_I ON INV_APPLICATION (APP_APPLICATION_ID) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_APPLICATION_AUD_PK_I ON INV_APPLICATION_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_CATEGORY_AUD_PK_I ON INV_CATEGORY_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_SYSTEM_TYPE_AUD_PK_I ON INV_SYSTEM_TYPE_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_FIELD_AUD_PK_I ON INV_FIELD_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_ADM_UNIT_AUD_PK_I ON INV_ADM_UNIT_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_COMMISSION_AUD_PK_I ON INV_COMMISSION_AUD (AUDIT_ID) TABLESPACE INVAI_INDEX;

CREATE UNIQUE INDEX INV_APPLICATION_CODE_UK_I ON INV_APPLICATION (CASE WHEN DELETED_AT IS NULL THEN CODE ELSE NULL END) TABLESPACE INVAI_INDEX;
CREATE UNIQUE INDEX INV_APPLICATION_PREFIX_UK_I ON INV_APPLICATION (CASE WHEN DELETED_AT IS NULL THEN PREFIX ELSE NULL END) TABLESPACE INVAI_INDEX;