GRANT SELECT, INSERT, UPDATE, DELETE ON INV_STATUS TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_CATEGORY TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_SYSTEM_TYPE TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_FIELD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_ADM_UNIT TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_COMMISSION TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APPLICATION TO WWW_INVAI;

GRANT SELECT, INSERT, UPDATE, DELETE ON INV_CATEGORY_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_SYSTEM_TYPE_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_FIELD_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_ADM_UNIT_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_COMMISSION_AUD TO WWW_INVAI;
GRANT SELECT, INSERT, UPDATE, DELETE ON INV_APPLICATION_AUD TO WWW_INVAI;

GRANT SELECT ON INV_STATUS_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_CATEGORY_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_SYSTEM_TYPE_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_FIELD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_ADM_UNIT_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_COMMISSION_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APPLICATION_SEQ TO WWW_INVAI;

GRANT SELECT ON INV_CATEGORY_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_SYSTEM_TYPE_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_FIELD_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_ADM_UNIT_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_COMMISSION_AUD_SEQ TO WWW_INVAI;
GRANT SELECT ON INV_APPLICATION_AUD_SEQ TO WWW_INVAI;