ALTER SESSION SET CONTAINER = XEPDB1;

CREATE TABLESPACE INVAI
    DATAFILE '/opt/oracle/oradata/INVAI.dbf'
    SIZE 100M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE USER INVAI IDENTIFIED BY oracle
    DEFAULT TABLESPACE INVAI
    TEMPORARY TABLESPACE TEMP;

ALTER USER INVAI QUOTA UNLIMITED ON INVAI;

GRANT CREATE SESSION TO INVAI;
GRANT CREATE TABLE TO INVAI;
GRANT CREATE SEQUENCE TO INVAI;
GRANT CREATE ANY INDEX TO INVAI;
GRANT CREATE VIEW TO INVAI;
GRANT CREATE PROCEDURE TO INVAI;
GRANT ALTER SESSION TO INVAI;

CREATE TABLESPACE INVAI_INDEX
    DATAFILE '/opt/oracle/oradata/invai_index.dbf'
    SIZE 100M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

ALTER USER INVAI QUOTA UNLIMITED ON INVAI_INDEX;

CREATE TABLESPACE INVAI_DADES
    DATAFILE '/opt/oracle/oradata/invai_dades.dbf'
    SIZE 100M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

ALTER USER INVAI QUOTA UNLIMITED ON INVAI_DADES;

CREATE TABLESPACE WWW_INVAI
    DATAFILE '/opt/oracle/oradata/www_invai.dbf'
    SIZE 100M
    AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE USER WWW_INVAI IDENTIFIED BY oracle
    DEFAULT TABLESPACE WWW_INVAI;

ALTER USER WWW_INVAI QUOTA UNLIMITED ON WWW_INVAI;

GRANT CREATE SESSION TO WWW_INVAI;
GRANT CREATE TABLE TO WWW_INVAI;
GRANT CREATE ANY INDEX TO WWW_INVAI;
GRANT CREATE VIEW TO WWW_INVAI;
GRANT CREATE PROCEDURE TO WWW_INVAI;
GRANT ALTER SESSION TO WWW_INVAI;

ALTER SESSION SET CURRENT_SCHEMA = INVAI;